In [1]:
import pandas as pd
df=pd.read_csv("ipl_ball_by_ball_data.csv")

In [2]:
df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [3]:
df.shape

(150460, 21)

In [4]:
len(df['match_id'].unique())

636

In [5]:
match_ids = df['match_id'].unique()
print(match_ids[:5])

[1 2 3 4 5]

In [6]:
match_df = df[df['match_id'] == 2]

In [7]:
match_df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
248,2,1,Mumbai Indians,Rising Pune Supergiant,1,1,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
249,2,1,Mumbai Indians,Rising Pune Supergiant,1,2,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
250,2,1,Mumbai Indians,Rising Pune Supergiant,1,3,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
251,2,1,Mumbai Indians,Rising Pune Supergiant,1,4,JC Buttler,PA Patel,AB Dinda,0,...,0,0,0,0,5,0,5,NaN,NaN,NaN
252,2,1,Mumbai Indians,Rising Pune Supergiant,1,5,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,2,2,Rising Pune Supergiant,Mumbai Indians,20,1,MS Dhoni,SPD Smith,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
491,2,2,Rising Pune Supergiant,Mumbai Indians,20,2,SPD Smith,MS Dhoni,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
492,2,2,Rising Pune Supergiant,Mumbai Indians,20,3,MS Dhoni,SPD Smith,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
493,2,2,Rising Pune Supergiant,Mumbai Indians,20,4,SPD Smith,MS Dhoni,KA Pollard,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
494,2,2,Rising Pune Supergiant,Mumbai Indians,20,5,SPD Smith,MS Dhoni,KA Pollard,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [8]:
match_df = match_df.sort_values(by=['inning', 'over', 'ball'])

In [9]:
match_df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
248,2,1,Mumbai Indians,Rising Pune Supergiant,1,1,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
249,2,1,Mumbai Indians,Rising Pune Supergiant,1,2,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
250,2,1,Mumbai Indians,Rising Pune Supergiant,1,3,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
251,2,1,Mumbai Indians,Rising Pune Supergiant,1,4,JC Buttler,PA Patel,AB Dinda,0,...,0,0,0,0,5,0,5,NaN,NaN,NaN
252,2,1,Mumbai Indians,Rising Pune Supergiant,1,5,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,2,2,Rising Pune Supergiant,Mumbai Indians,20,1,MS Dhoni,SPD Smith,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
491,2,2,Rising Pune Supergiant,Mumbai Indians,20,2,SPD Smith,MS Dhoni,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
492,2,2,Rising Pune Supergiant,Mumbai Indians,20,3,MS Dhoni,SPD Smith,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
493,2,2,Rising Pune Supergiant,Mumbai Indians,20,4,SPD Smith,MS Dhoni,KA Pollard,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
494,2,2,Rising Pune Supergiant,Mumbai Indians,20,5,SPD Smith,MS Dhoni,KA Pollard,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [10]:
match_df = match_df.reset_index(drop=True)

In [11]:
match_df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,2,1,Mumbai Indians,Rising Pune Supergiant,1,1,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
1,2,1,Mumbai Indians,Rising Pune Supergiant,1,2,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,2,1,Mumbai Indians,Rising Pune Supergiant,1,3,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
3,2,1,Mumbai Indians,Rising Pune Supergiant,1,4,JC Buttler,PA Patel,AB Dinda,0,...,0,0,0,0,5,0,5,NaN,NaN,NaN
4,2,1,Mumbai Indians,Rising Pune Supergiant,1,5,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,2,2,Rising Pune Supergiant,Mumbai Indians,20,1,MS Dhoni,SPD Smith,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
243,2,2,Rising Pune Supergiant,Mumbai Indians,20,2,SPD Smith,MS Dhoni,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
244,2,2,Rising Pune Supergiant,Mumbai Indians,20,3,MS Dhoni,SPD Smith,KA Pollard,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
245,2,2,Rising Pune Supergiant,Mumbai Indians,20,4,SPD Smith,MS Dhoni,KA Pollard,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
246,2,2,Rising Pune Supergiant,Mumbai Indians,20,5,SPD Smith,MS Dhoni,KA Pollard,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [12]:
match_df['is_wicket'] = match_df['player_dismissed'].notna().astype(int)

In [13]:
match_df.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder,is_wicket
0,2,1,Mumbai Indians,Rising Pune Supergiant,1,1,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,1,1,NaN,NaN,NaN,0
1,2,1,Mumbai Indians,Rising Pune Supergiant,1,2,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,0,0,0,NaN,NaN,NaN,0
2,2,1,Mumbai Indians,Rising Pune Supergiant,1,3,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,1,0,1,NaN,NaN,NaN,0
3,2,1,Mumbai Indians,Rising Pune Supergiant,1,4,JC Buttler,PA Patel,AB Dinda,0,...,0,0,0,5,0,5,NaN,NaN,NaN,0
4,2,1,Mumbai Indians,Rising Pune Supergiant,1,5,PA Patel,JC Buttler,AB Dinda,0,...,0,0,0,4,0,4,NaN,NaN,NaN,0

In [14]:
match_df[['inning','over','ball','total_runs','is_wicket']].head(20)

    inning  over  ball  total_runs  is_wicket
0        1     1     1           1          0
1        1     1     2           0          0
2        1     1     3           1          0
3        1     1     4           5          0
4        1     1     5           4          0
5        1     1     6           0          0
6        1     1     7           0          0
7        1     2     1           4          0
8        1     2     2           0          0
9        1     2     3           4          0
10       1     2     4           0          0
11       1     2     5           0          0
12       1     2     6           0          0
13       1     3     1           0          0
14       1     3     2           4          0
15       1     3     3           0          0
16       1     3     4           0          0
17       1     3     5           4          0
18       1     3     6           1          0
19       1     4     1           1          0

In [15]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\acer\anaconda3\envs\cleanlab\lib\site-packages (9.6.0)

In [16]:
import mysql.connector

conn = mysql.connector.connect(host="localhost",user="root",password="shiyam@123",  
    database="ipl_db")

print("Connected successfully")

Connected successfully

In [17]:
cursor = conn.cursor()

In [18]:
import time

query = """INSERT INTO ipl_live 
(match_id, inning, over_num, ball_num, batsman, bowler, total_runs, is_wicket)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"""

for _, row in match_df.iterrows():
    values = (row['match_id'],row['inning'],row['over'],row['ball'],row['batsman'],
    row['bowler'],row['total_runs'],row['is_wicket'])

cursor.execute(query, values)
conn.commit()

print(f"Inserted: Over {row['over']}.{row['ball']} | Runs: {row['total_runs']}")
time.sleep(1)

Inserted: Over 20.5 | Runs: 6